[package]
edition = "2018"
name    = "helloworld-tonic"
version = "0.1.0"

[dependencies]
prost        = "0.8"
tokio        = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.7"
tonic        = "0.5"
tonic-web    = "0.1.0"

[build-dependencies]
tonic-build = "0.5"
